Updating to Swift 4.2 & Xcode 10
urbn/URBNMrkDwn pull request #7
Opened 2018-11-13 15:22 UTC by codecaffeine

Updating to Swift 4.2 & Xcode 10

2019-02-04 16:37 UTC, Dutcher approved these changes

2019-02-04 18:30 UTC, Lloyd1nSpace-zz requested changes

2019-02-04 18:30 UTC, Lloyd1nSpace commented on Example/Podfile
> +  platform :tvos, '9.0'
Is this supposed to be tvOS 10?

2019-02-05 14:25 UTC, codecaffeine commented on Example/Podfile
> +  platform :tvos, '9.0'
The AssistedSellingTVApp technically support tvOS 9. There’s been no request to update it.

2019-02-05 14:55 UTC, Lloyd1nSpace-zz approved these changes

2019-02-05 14:55 UTC, merged